### ISSUE TITLE
Missing menubar_related_categories.tpl?

### ISSUE THREAD

**Issue by ablivio** [Piwigo/piwigo-smartpocket#2]
Hi,

I had the following error message:

`Fatal error: Uncaught --> Smarty: Unable to load template file 'menubar_related_categories.tpl' in 'menubar.tpl' <-- thrown in /(edited)/include/smarty/libs/sysplugins/smarty_internal_template.php on line 139`

Creating an empty menubar_related_categories.tpl in /(edited)/themes/smartpocket/template solved this issue.

Hope this helps!

**Comment by 7tonin** [comment]
Hi,
It is possible to make a copy from the one in /(edited)/themes/**default**/template/
But, right now, in order to unfold nicely in the menu, it still misses CSS layout.
