### ISSUE TITLE
Swipped pictures are not logged in history

### ISSUE THREAD

**Issue by 7tonin** [Piwigo/piwigo-smartpocket#4]
When swipping between pictures, this error appears when debuging website with the browser.
XHR POST https://_my_piwigo_._net_/ws.php?format=json&method=smartpocket.images.logHistory
[HTTP/1.1 501 Method name is not valid 24ms]

Looks like method is not loaded by ws.php

This bug is the reason why swipped pictures are not logged in history. 

Poll: who cares about it ?

**Comment by 7tonin** [comment]
Solved this issue by tweaking (piwigo)/ws.php code. I mean copying some code from the theme in it.
That's around line 21.
```
.../...
include_once(PHPWG_ROOT_PATH.'include/ws_core.inc.php');
<<<HERE>>>
add_event_handler('ws_add_methods', 'ws_addDefaultMethods');
add_event_handler('ws_invoke_allowed', 'ws_isInvokeAllowed', EVENT_HANDLER_PRIORITY_NEUTRAL, 3);
.../...
```

```
/* HACK BEGIN */
add_event_handler('loc_end_section_init', 'sp_end_section_init');
function sp_end_section_init()
{
.../...
}

add_event_handler('ws_add_methods', 'sp_add_methods');
function sp_add_methods($arr)
{
.../...
}

function ws_sp_log_history($params, &$service)
{
.../...
}

/* HACK END */
```
I cannot explain why ws.php looks like missing some event_handlers.

**Comment by plegall** [comment]
I gave an answer on https://github.com/Piwigo/Piwigo/pull/1421#issuecomment-1199664108

**Comment by plegall** [comment]
I've added method `pwg.history.log` method in Piwigo core. Let's use it in SmartPocket now.
